pipeline {
  agent any
  environment {
    GIT_SSH_COMMAND = 'ssh -i ~/.ssh/ets-gpkg12'
  }
  tools {
    maven 'mvn'
    jdk 'JDK 8'
  }
  stages {
    stage('Preparation') {
      steps{
        deleteDir()
        sh 'git clone git@github.com:opengeospatial/ets-gpkg12.git .'
      }
    }
    stage('Release') {
      steps{
        sh 'mvn --version'
        sh 'mvn -Dresume=false -DdryRun=true release:prepare -DreleaseVersion=${releaseVersion} -DdevelopmentVersion=${developmentVersion}'
        sh 'mvn -Dresume=false release:prepare release:perform -Psign-artifacts-with-ogc -DreleaseVersion=${releaseVersion} -DdevelopmentVersion=${developmentVersion}'
      }
    }
    stage('Publication of site') {
      steps{
        sh 'mvn --version'
        sh 'git checkout ${releaseVersion}'
        sh 'mvn clean install site site:stage scm-publish:publish-scm'
      }
    }
    stage('Results') {
      steps{
        junit '**/target/surefire-reports/TEST-*.xml'
        archive 'target/*'
      }
    }
  }
}